const productos = [
  {
    id: 'p1',
    fotos: [
      require('../assets/img/Imgproductos/Base de gotero Salome.webp'),
      require('../assets/img/Imgproductos/Bálsamo premium Salomé.webp'),
      require('../assets/img/Imgproductos/Lipgloss kis me ushas.webp'),
    ],
    nombre: 'Producto 1',
    precioMayor: '100',
    precioDetal: '120',
    marca: 'Salome',
    stock: 20,
    descripcion: 'Base de gotero hidratante para todo tipo de piel.',
    cantidadMayor: 6,
  },
  {
    id: 'p2',
    fotos: [
      require('../assets/img/Imgproductos/Bálsamo premium Salomé.webp'),
      require('../assets/img/Imgproductos/Base de gotero Salome.webp'),
      require('../assets/img/Imgproductos/Lipgloss kis me ushas.webp'),
    ],
    nombre: 'Producto 2',
    precioMayor: '200',
    precioDetal: '240',
    marca: 'Salomé',
    stock: 15,
    descripcion: 'Bálsamo labial premium con ingredientes naturales.',
    cantidadMayor: 12,
  },
  {
    id: 'p3',
   fotos: [
     require('../assets/img/Imgproductos/Lipgloss kis me ushas.webp'),
      require('../assets/img/Imgproductos/Base de gotero Salome.webp'),
      require('../assets/img/Imgproductos/Bálsamo premium Salomé.webp'),
    ],
    nombre: 'Producto 3',
    precioMayor: '150',
    precioDetal: '180',
    marca: 'Ushas',
    stock: 30,
    descripcion: 'Lipgloss de larga duración con acabado brillante.',
    cantidadMayor: 10,
  },
];

const productos2 = [
{ 
    id: 'p2-1',
    fotos: [
      require('../assets/img/Imgproductos/Base de gotero Salome.webp'),
      require('../assets/img/Imgproductos/Bálsamo premium Salomé.webp'),
      require('../assets/img/Imgproductos/Lipgloss kis me ushas.webp'),
    ],
    nombre: 'Producto 1',
    precioMayor: '100',
    precioDetal: '120',
    marca: 'Salome',
    stock: 20,
    descripcion: 'Base de gotero hidratante para todo tipo de piel.',
    cantidadMayor: 6,
  },
  {
    id: 'p2-2',
    fotos: [
      require('../assets/img/Imgproductos/Bálsamo premium Salomé.webp'),
      require('../assets/img/Imgproductos/Base de gotero Salome.webp'),
      require('../assets/img/Imgproductos/Lipgloss kis me ushas.webp'),
    ],
    nombre: 'Producto 2',
    precioMayor: '200',
    precioDetal: '240',
    marca: 'Salomé',
    stock: 15,
    descripcion: 'Bálsamo labial premium con ingredientes naturales.',
    cantidadMayor: 12,
  },
  {
    id: 'p2-3',
    fotos: [
      require('../assets/img/Imgproductos/Lipgloss kis me ushas.webp'),
      require('../assets/img/Imgproductos/Base de gotero Salome.webp'),
      require('../assets/img/Imgproductos/Bálsamo premium Salomé.webp'),
    ],
    nombre: 'Producto 3',
    precioMayor: '150',
    precioDetal: '180',
    marca: 'Ushas',
    stock: 30,
    descripcion: 'Lipgloss de larga duración con acabado brillante.',
    cantidadMayor: 10,
  },
  {
    id: 'p2-4',
    fotos: [
      require('../assets/img/Imgproductos/Contorno de ojos kojic acid.webp'),
      require('../assets/img/Imgproductos/Polvo suelto premium Salomé.webp'),
      require('../assets/img/Imgproductos/Labial+lapiz ushas.webp'),
    ],
    nombre: 'Producto 4',
    precioMayor: '150',
    precioDetal: '180',
    marca: 'Ushas',
    stock: 25,
    descripcion: 'Lipgloss de larga duración con acabado brillante.',
    cantidadMayor: 10,
  },
  {
    id: 'p2-5',
    fotos: [
      require('../assets/img/Imgproductos/Polvo suelto premium Salomé.webp'),
      require('../assets/img/Imgproductos/Labial+lapiz ushas.webp'),
      require('../assets/img/Imgproductos/Contorno de ojos kojic acid.webp'),
    ],
    nombre: 'Producto 5',
    precioMayor: '150',
    precioDetal: '180',
    marca: 'Ushas',
    stock: 25,
    descripcion: 'Lipgloss de larga duración con acabado brillante.',
    cantidadMayor: 10,
  },
  {
    id: 'p2-6',
    fotos: [
      require('../assets/img/Imgproductos/Labial+lapiz ushas.webp'),
     require('../assets/img/Imgproductos/Polvo suelto premium Salomé.webp'),
      require('../assets/img/Imgproductos/Contorno de ojos kojic acid.webp'),
    ],
    nombre: 'Producto 6',
    precioMayor: '150',
    precioDetal: '180',
    marca: 'Ushas',
    stock: 25,
    descripcion: 'Lipgloss de larga duración con acabado brillante.',
    cantidadMayor: 10,
  },
];
export { productos, productos2 };